version: "3.3"
services:
  app:
    image: simpleapi-app
    ports:
      - 5000:5000
    build:
      context: .
      dockerfile: ./provision/app/Dockerfile
    command: npm run start
    env_file:
      - .env
    stdin_open: true
    tty: true
    volumes:
      - nodemodules-simpleapi:/usr/src/node_modules
      - .:/usr/src
    depends_on:
      - db

  db:
    restart: always
    image: postgres:12.0
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data
      - .:/usr/src

  pgadmin:
    container_name: pgadmin-simpleapi
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  db:
  nodemodules-simpleapi: